version: "3.8"
services:
  web:
    container_name: lara9web
    image: nginx:1.21.4-alpine
    ports:
      - "8090:80"
    depends_on:
      - app
      - db
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    networks:
      - appnet
  app:
    container_name: lara9app
    build: ./docker/php
    depends_on:
      - db
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    networks:
      - appnet
  db:
    container_name: lara9db
    image: mysql:8.0
    ports:
      - 23306:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.conf
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
